name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  VCINSTALLDIR: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/
  Qt5_DIR: Qt\5.13.1\msvc2017_64\lib\cmake\Qt5\
  QTDIR: Qt\5.13.1\msvc2017_64\

jobs:
  windows:
    timeout-minutes: 15
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare
      working-directory: build
      shell: cmd
      run: |
        curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
        qt-unified-windows-x86-online.exe --verbose --script ..\ci\qt.qs
    - name: Configure
      working-directory: build
      shell: cmd
      run: cmake -DCPACK_IFW_ROOT=Qt/Tools/QtInstallerFramework/3.1 -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" ..

    - name: Compile
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release -j 4

    - name: Package
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release --target package

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/maximum_trainer_installer.exe
